[package]
name = "deskpi-fan-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive", "cargo"] }
libudev = "0.3.0"
serialport = "4.2.0"
